---
- name: "user : create/manage group for {{ user.name }}."
  group:
    name: "{{ user.group | default(user.name) }}"

- name: "user : create / manage user {{ user.name }}."
  user:
    name: "{{ user.name }}"
    shell: "{{ user.shell | default(users_default_shell) }}"
    home: "{{ user.home | default(omit) }}"
    move_home: "{{ user.move_home | default(omit) }}"
    password: "{{ user.password | default(omit) }}"
    group: "{{ user.group | default(user.name) }}"
    groups: "{{ user.groups | default(users_default_groups) }}"
    append: "{{ user.append | default('no') }}"
  register: _user_result

- debug:
    var: _user_result

- name: "user : manage authorized keys for {{ user.name }}."
  include_tasks: authorized_key.yml
  with_items: "{{ user.authorized_keys | default([]) }}"
  vars:
  loop_control:
    loop_var: authorized_key

- name: "user : manage history."
  blockinfile:
    path: "{{ _user_result.home }}/.bashrc"
    marker: "# {mark} tobias_richter.users history"
    state: "{{ 'present' if not (user.history | default('yes') | bool) else 'absent' }}"
    block: |
      set +o history

- name: "user : remove history."
  file:
    path: "{{ _user_result.home }}/.bash_history"
    state: absent
  when: not (user.history | default('yes') | bool)
